services:
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      context: ./
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
  pg:
    image: postgres:17.6-bookworm
    environment:
      POSTGRES_DB: $db__name
      POSTGRES_USER: $db__username
      POSTGRES_PASSWORD: $db__password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg_admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - pg
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery --app app.celery.celery_app:app worker -l info --pool=prefork --concurrency=10
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./storage:/app/storage

volumes:
  postgres_data: