"""add path field

Revision ID: 4d1af99f8a13
Revises: 5f4670c2d10a
Create Date: 2026-03-11 16:09:18.709326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d1af99f8a13"
down_revision: Union[str, Sequence[str], None] = "5f4670c2d10a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos", sa.Column("path", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "path")
    # ### end Alembic commands ###
